config/routes.rb
Rails.application.routes.draw do

  get 'events/info'
  get 'events/:id/home', to: 'events#home'
  get 'keywords/filter', to: 'keywords#filter'

  devise_for :users, :controllers => { registrations: 'registrations', sessions: 'sessions' }

resources :events do
  resources :acts
  resources :venues
  resources :timeslots
  resources :days
  resources :keywords
end

  resources :bookings
  resources :users

  root to: 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :name, presence: true

  has_many :acts
  has_many :venues
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :set_theme

  before_action :authenticate_user!, except: [:index, :home]

  def index
    @events = Event.all
    render layout: false
  end

  def show
    @event = Event.find(params[:id])

    require 'date'

    date_from  = @event.start_date
    date_to    = @event.end_date
    @date_range = date_from..date_to

    @days = @date_range.map(&:mday)

    @booking = Booking.new
  end

  def info
    @event = Event.find(params[:id])
  end

  def home
    @event = Event.find(params[:id])

    render template: template_to_render
  end


  def edit 
    @event = Event.find(params[:id])
  end

  def new 
    @event = Event.new
    render layout: false
  end

  def create
    Event.create(event_params)
    redirect_to events_path
  end


  def update
    event = Event.find(params[:id])
    event.update(event_params)
    redirect_to event_path(event)
  end

  private

    def template_to_render
      if template_exists?("../../themes/#{@event.theme}/home")
        "../../themes/#{@event.theme}/home"
      else
        "/events/home"
      end
    end

  def set_theme
    if params[:event_id]
    event = Event.find(params[:event_id])
  elsif params[:id]
    event = Event.find(params[:id])
  else
    return
  end
    theme = event.theme
    prepend_view_path "app/themes/#{theme}"
    self.class.layout "../../themes/#{theme}/layout"
  end

  def event_params
    params.require(:event).permit(:name, :start_date, :location, :end_date, :description, :theme, :act_alias, :venue_alias)  
  end
  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= form_for(@event) do |f| %>

<%= f.label :name %><br>
<%= f.text_field :name %><br>

<%= f.label :location %><br>
<%= f.text_field :location %><br>

<%= f.label :description, 'Description' %><br>
<%= f.text_area :description %><br>

<%= f.label :act_alias, "Default term for 'acts'" %><br>
<%= f.text_field :act_alias %><br>

<%= f.label :venue_alias, "Default term for 'venues'" %><br>
<%= f.text_field :venue_alias %><br>

<%= f.label :start_date %><br>
<%= f.date_select :start_date %><br>

<%= f.label :end_date %><br>
<%= f.date_select :end_date %><br>

<%= f.label :theme %><br>
<%= f.radio_button :theme, "default" %> Default<br>
<%= f.radio_button :theme, "conference" %> Conference<br>
<%= f.radio_button :theme, "fields" %> Fields<br><br>

<%= f.submit 'Save' %>

<% end %>

app/views/events/home.html.erb
<div class="nav-buttons">

  <%= link_to 'My Schedule', users_path(event_id: @event.id) %>
  <span class="mobile-lineup">
  <%= link_to 'Full Lineup', event_day_path(@event, @event.start_date.day) %>
  </span>
  <span class="big-lineup">
  <%= link_to 'Full Lineup', event_path(@event) %>
  </span>
  </div>
<section class="home-box">
  
<div class="box box-1"><%= link_to @event.act_alias, event_acts_path(@event) %></div>
<div class="box box-2"><%= link_to @event.venue_alias, event_venues_path(@event) %></div>
</section>
<section class="home-box">
<div class="box box-3"><%= link_to 'News', '/news' %></div>
<div class="box box-4"><%= link_to 'Info', events_info_path(id: @event.id) %></div>


</section>

app/views/events/index.html.erb
<style>
  body {
    font-family: Helvetica;
    padding: 30px;
  }
  a {
    color: navy;
  }
</style>

<h1> Event Listings </h1>

<% @events.each do |event| %>

<h3><%= link_to event.name, controller: :events, action: :home, id: event.id, event_id: event.id %></h3>
<%= event.description %><br><br>

<% end %>
<br><br>
<%= link_to "New Event", new_event_path %>

app/views/events/info.html.erb
<div id="map" style="height:300px; width:500px; float: left; margin: 20px;"></div>
  <script>
    var map = new GMaps({
      el: '#map',
      lat: 55.636698,
      lng: -2.793565, 
    });


    map.addMarker({
      lat: 55.636698,
      lng: -2.793565,
      title: 'Lima',
      infoWindow: {
        content: '<p>HTML Content</p>'
      }
    });
  </script>
<br><br>
  <h1>Find Us</h1>
  Borders Fest is located just outside of Galashiels in the Scottish Borders. You can get to us via rail at Galashiels Railway Station, by bus or by car. There will be free shuttle buses from Galashiels town centre to the festival site running throughout the weekend.

app/views/events/new.html.erb
<style>
  body {
    font-family: Helvetica;
    padding: 30px;
  }
  a {
    color: navy;
  }
  label {
    margin: 5px 0;
    display: inline-block;
  }
</style>
<h1>Create New Event</h1>

<%= form_for(@event) do |f| %>

<%= f.label :name %><br>
<%= f.text_field :name %><br>

<%= f.label :location %><br>
<%= f.text_field :location %><br>

<%= f.label :description, 'Description' %><br>
<%= f.text_area :description %><br>

<%= f.label :act_alias, "Default term for 'acts'" %><br>
<%= f.text_field :act_alias %><br>

<%= f.label :venue_alias, "Default term for 'venues'" %><br>
<%= f.text_field :venue_alias %><br>

<%= f.label :start_date %><br>
<%= f.date_select :start_date %><br>

<%= f.label :end_date %><br>
<%= f.date_select :end_date %><br>

<%= f.label :theme %><br>
<%= f.radio_button :theme, "default" %> Default<br>
<%= f.radio_button :theme, "conference" %> Conference<br>
<%= f.radio_button :theme, "fields" %> Fields<br><br>

<%= f.submit 'Save' %>

<% end %>

app/views/events/show.html.erb
<section class="lineup">
  <ul class="timetable">
    <% @date_range.each do |date| %>
    <li class="date"><h1><%= date.strftime("%A") %></h1><%= date.strftime("%B #{date.day.ordinalize}") %></li>
    <% end %>
    <br><br>

    <% @event.venues.each do |venue| %>

    <% days_list = [] %>

    <% @date_range.each do |date| %>

    <% collection = venue.timeslots.select { |t| t.start_time.day == date.day } %>
    <% days_list << collection %>

    <% end %>


<!--     <%# fri = venue.timeslots.select { |t| t.start_time.day == 10 } %>
    <%# sat = venue.timeslots.select { |t| t.start_time.day == 11 } %>
    <%# sun = venue.timeslots.select { |t| t.start_time.day == 12 } %>
    <%# days = [fri, sat, sun] %> -->
    

    <li class="venue_name">
<span class="venue_name_text">
    <h4>
  <%= link_to venue.name, event_venue_path(@event, venue) %></h4></span><br></li>
  </ul>

  <ul class="days">
    <li><% days_list.each do |day| %>

      <% day.sort_by{|d| d.start_time}.reverse.each do |timeslot| %>
      <div class="each-time">
        <% if timeslot.act.headline_image.present? %>
        <%= link_to image_tag(timeslot.act.headline_image, class: "timetable_image"), event_act_path(@event, timeslot.act) %><br>
        <% else %>
        <h3><%= link_to timeslot.act.name, event_act_path(@event, timeslot.act) %></h3>
        <% end %>

        <span class="time-hover">
          <%= timeslot.start_time.strftime("%l:%M %p") %> - <%= timeslot.end_time.strftime("%l:%M %p")  %>
        

        <% if current_user.timeslots.find_by_id(timeslot.id) != nil %>

        <%= button_to '', booking_path(current_user.bookings.find_by_timeslot_id(timeslot.id)), method: :delete, class: "unschedule", title: "Remove from My Schedule" %>
        <% else %>
        <%= form_for(@booking, :html => {class: "schedule_form"}) do |f| %> 
        <% if @booking.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this act from being saved:</h2>

          <ul>
            <% @booking.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>

        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.hidden_field :timeslot_id, value: timeslot.id %>
        <%= f.submit '', class: "schedule", title: "Add to My Schedule" %>

        <% end %>
        </span>

        <% end %>
      </div>
      <% end %>
      <li>

        <% end %>
      </ul>
      <% end %>

    </section>