config/routes.rb
Rails.application.routes.draw do

  get 'events/info'
  get 'events/:id/home', to: 'events#home'
  get 'keywords/filter', to: 'keywords#filter'

  devise_for :users, :controllers => { registrations: 'registrations', sessions: 'sessions' }

resources :events do
  resources :acts
  resources :venues
  resources :timeslots
  resources :days
  resources :keywords
end

  resources :bookings
  resources :users

  root to: 'events#index'

end

app/models/venue.rb
class Venue < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: true


  belongs_to :event

  has_many :timeslots, dependent: :destroy
  has_many :acts, through: :timeslots

  def html
    renderer = Redcarpet::Render::HTML.new(render_options = {})
    markdown = Redcarpet::Markdown.new(renderer, extensions = {})
    markdown.render(self.description).html_safe
  end
  
end

app/controllers/venues_controller.rb
class VenuesController < EventsController
  before_action :authenticate_user!, except: :index

  def index
    @event = Event.find(params[:event_id])
    @venues = @event.venues.all
  end

  def show 
    @venue = Venue.find(params[:id])
    @timeslots = @venue.timeslots.all.order(:start_time)
    @event = Event.find(params[:event_id])
  end

  def new
    @venue = Venue.new(event_id: @event.id)
  end

  def create 
    @venue = Venue.new(venue_params)
    @event = @venue.event

    respond_to do |format|
      if @venue.save
        format.html { redirect_to venue_path(@venue, event: @event), notice: 'Stage was successfully created.' }
        # format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        # format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit 
    @venue = Venue.find(params[:id])
  end

  def update
    venue = Venue.find(params[:id])
    venue.update(venue_params)
    redirect_to venue_path(venue)
  end

  def destroy
    venue = Venue.find(params[:id])
    venue.destroy
    redirect_to(venues_path)
  end



  private

  def venue_params
    params.require(:venue).permit(:name, :description, :location, :venue_image, :event_id)  
  end

end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_form.html.erb
<%= form_for(@venue) do |f| %>
<% if @venue.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@venue.errors.count, "error") %> prohibited this stage from being saved:</h2>

  <ul>
    <% @venue.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<%= f.label :event_id, 'Event' %>
<%= f.select :event_id, Event.all.collect { |e| [ e.name, e.id ] } %><br>

<%= f.label :name %><br>
<%= f.text_field :name %><br>

<%= f.label :venue_image, 'Image URL' %><br>
<%= f.text_field :venue_image %><br>

<%= f.label :description, 'Description' %><br>
<%= f.text_area :description %><br>

<%= f.label :location, 'Location' %><br>
<%= f.text_field :location %><br>

<%= f.submit 'Save' %>

<% end %>

app/views/venues/edit.html.erb
<h1>Edit Stage Profile</h1>

<%= render 'form' %>

app/views/venues/index.html.erb
<h1><%=@event.venue_alias%></h1>
<% if can? :create, Venue %>
<%= link_to 'Add Stage', new_event_venue_path(@event) %><br><br>
<% end %>
<% @venues.each do |venue| %>
<%= link_to venue.name, event_venue_path(@event, venue) %>
<% if can? :update, Venue %>
/ <%= link_to 'Edit', edit_event_venue_path(@event, venue) %>
<% end %>
<% if can? :delete, Venue %>
/ <%= link_to 'Delete', event_venue_path(@event, venue), method: :delete, data: {confirm: 'Are you sure you want to delete this venue and all of its time slots?'} %>
<% end %>
<br><br>
<% end %>
<br>
<%= link_to 'Back', :back %>

app/views/venues/new.html.erb
<h1>Add Stage</h1>

<%= render 'form' %>

app/views/venues/show.html.erb
<h2><%= @venue.name %></h2>

<% if @venue.venue_image %>
<%= image_tag(@venue.venue_image, class: "act-image") %><br>
<% end %>
<%= @venue.html %><br><br>
<h4>Location:</h4>
<%= @venue.location %><br><br>
<h4>Times:</h4>
<% @timeslots.each do |timeslot| %>
  <%= timeslot.start_time.strftime("%A %l:%M %p") %> - <%= timeslot.end_time.strftime("%l:%M %p")  %>, <%= timeslot.act.name %> 
  <% if can? :update, Timeslot %><%= link_to 'Edit', edit_event_timeslot_path(@event, timeslot) %> - 
  <% end %>
  <% if can? :delete, Timeslot %>
  <%= link_to 'Delete', event_timeslot_path(@event, timeslot), method: :delete, data: {confirm: 'Are you sure you want to delete this time slot?'} %><br>
  <% end %><br>
<% end %>
<br>
<%= link_to 'Back', :back %>
<br><br>

<% if can? :update, Venue %>
<%= link_to "Edit Stage Profile", edit_event_venue_path(@event, @venue) %> -
<% end %> 
<% if can? :create, Timeslot %> 
<%= link_to "Add Performance Times", {:controller => "timeslots", :action => "new", :venue_id => @venue.id } %> 
<% end %>