config/routes.rb
Rails.application.routes.draw do

  get 'events/info'
  get 'events/:id/home', to: 'events#home'
  get 'keywords/filter', to: 'keywords#filter'

  devise_for :users, :controllers => { registrations: 'registrations', sessions: 'sessions' }

resources :events do
  resources :acts
  resources :venues
  resources :timeslots
  resources :days
  resources :keywords
end

  resources :bookings
  resources :users

  root to: 'events#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EventApp</title>
  <%= stylesheet_link_tag    'normalize', media: 'all', 'data-turbolinks-track' => true %>

<%= stylesheet_link_tag    'style', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link href='https://fonts.googleapis.com/css?family=Arvo:400,700,400italic|Caveat+Brush' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>


  <script src="http://maps.google.com/maps/api/js"></script>
    <script src="gmaps.js"></script>

</head>
<body>
<div class="page-wrap">
<header>

<nav>
<%= link_to 'Home', controller: :events, action: :home, id: @event.id %>
</nav>

  <div class="login">
    <% if current_user %>
    <%= current_user.name %> | 
    <%= link_to 'Profile', user_path(current_user, event_id: @event.id) %> | 
    <%= link_to 'Log Out', destroy_user_session_path(event_id: @event.id), method: :delete %>
    <% else %>
    <%= link_to 'Sign In', new_user_session_path(event_id: @event.id) %> | 
    <%= link_to 'Register', new_user_registration_path(event_id: @event.id) %>
    <% end %>
  </div>


</header>

<div class="logo">
<%= link_to "#{@event.name.upcase}", event_path(@event) %>
</div>


<section class="main">

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</section>
</div>
<footer>
<%= link_to "#{@event.act_alias} A-Z", event_acts_path(@event) %> / 
<%= link_to @event.venue_alias, event_venues_path(@event) %>
<% if can? :create, Act %>
 / <%= link_to 'Add Act', new_event_act_path(@event) %> /
<% end %>
<% if can? :create, Venue %>
<%= link_to 'Add Stage', new_event_venue_path(@event) %> /
<% end %>
<% if can? :update, Event %>
<%= link_to 'Edit Event', "../../events/#{@event.id}/edit" %> /
<% end %>
<% if can? :create, Keyword %>
<%= link_to 'Manage Keywords', event_keywords_path(@event) %><br>
<% end %>
</footer>
</body>
</html>