config/routes.rb
Rails.application.routes.draw do

  get 'events/info'
  get 'events/:id/home', to: 'events#home'
  get 'keywords/filter', to: 'keywords#filter'

  devise_for :users, :controllers => { registrations: 'registrations', sessions: 'sessions' }

resources :events do
  resources :acts
  resources :venues
  resources :timeslots
  resources :days
  resources :keywords
end

  resources :bookings
  resources :users

  root to: 'events#index'

end

app/models/act.rb
class Act < ActiveRecord::Base

validates :name, presence: true
validates :name, uniqueness: true 
belongs_to :event

has_many :timeslots, dependent: :destroy
has_many :venues, through: :timeslots

has_and_belongs_to_many :keywords

def html
  renderer = Redcarpet::Render::HTML.new(render_options = {})
  markdown = Redcarpet::Markdown.new(renderer, extensions = {})
  markdown.render(self.description).html_safe
end

end

app/controllers/acts_controller.rb
class ActsController < EventsController


  before_action :authenticate_user!, except: :index
  
  def index
    @event = Event.find(params[:event_id])
    @acts = @event.acts.all.order(:name)
    @keywords = Keyword.all.select {|k| k.acts.any?{|a| a.event == @event }}

  end

  def show 
    @act = Act.find(params[:id])
    @booking = Booking.new
    @event = Event.find(params[:event_id])
  end

  def new
    @event = Event.find(params[:event_id])
    @act = Act.new(event_id: @event.id)
    @keywords = Keyword.all
  end

  def create 
    @act = Act.new(act_params)
    params[:act][:keyword_ids] ||= []
    keyword = Keyword.find(params[:act][:keyword_ids]) 
    @act.keywords = keyword
    @event = @act.event
    respond_to do |format|
      if @act.save
        format.html { redirect_to event_act_path(@event, @act), notice: 'Act was successfully created.' }
        # format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        # format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
    
  end

  def edit 
    @act = Act.find(params[:id])
    @keywords = Keyword.all
    @event = @act.event
  end

  def update
    act = Act.find(params[:id])
    act.update(act_params)
    params[:act][:keyword_ids] ||= []
    keyword = Keyword.find(params[:act][:keyword_ids]) 
    act.keywords = keyword
    @event = act.event
    redirect_to event_act_path(@event, act)
  end

  def destroy
    act = Act.find(params[:id])
    @event = act.event
    act.destroy
    redirect_to(event_acts_path(@event))
  end



  private

  def act_params
    params.require(:act).permit(:name, :description, :act_image, :headline_image, :event_id, { :keywords => []})  
  end


end

app/helpers/acts_helper.rb
module ActsHelper
end

app/views/acts/_form.html.erb
<%= form_for([@event, @act]) do |f| %>
    <% if @act.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@act.errors.count, "error") %> prohibited this act from being saved:</h2>

        <ul>
        <% @act.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.label :event_id, 'Event' %>
    <%= f.select :event_id, Event.all.collect { |e| [ e.name, e.id ] } %><br>


    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
  
    <%= f.label :act_image, 'Profile Image URL' %><br>
    <%= f.text_field :act_image %><br>

    <%= f.label :headline_image, 'Headline Image URL' %><br>
    <%= f.text_field :headline_image %><br>

    <%= f.label :description, 'Bio' %><br>
    <%= f.text_area :description, rows: 10, cols: 40 %><br>

    <%= f.label 'Keywords' %><br>
    <% @keywords.each do |keyword| %>
    <%= check_box_tag "act[keyword_ids][]", keyword.id, @act.keywords.include?(keyword) %>
    <%= keyword.name %>
    <% end %><br>

    <%= f.submit 'Save' %>

<% end %>

app/views/acts/edit.html.erb
<h1>Edit Act Profile</h1>

<%= render 'form' %>

app/views/acts/index.html.erb
<h1><%=@event.act_alias%> A-Z</h1>
<% if can? :create, Act %>
<%= link_to 'Add Act', new_event_act_path %><br><br>
<% end %>

Filter by tag:<br> 

<%= form_tag({controller: "keywords", action: "filter"}, method: "get") do %>

<div class="filter">
<%= select_tag(:keyword_select, options_for_select(@keywords.each.collect { |k| [ k.name, k.id ] })) %>
</div>
<%= hidden_field_tag :event_id, @event.id %>
<%= submit_tag(value = 'Go', class: "filter-button") %>
<% end %>


<br>


<% @acts.each do |act| %>
<%= link_to act.name, event_act_path(@event, act) %>
<% if can? :update, Act %>
/ <%= link_to 'Edit', edit_event_act_path(@event, act) %>
<% end %>
<% if can? :delete, Act %>
/ <%= link_to 'Delete', event_act_path(@event, act), method: :delete, data: {confirm: 'Are you sure you want to delete this act and all of its time slots?'} %><% end %>
<br><br>

<% end %>
<br>
<%= link_to 'Back', :back %>

app/views/acts/new.html.erb
<h1>Add Act</h1>

<%= render 'form' %>

app/views/acts/show.html.erb
<h2><%= @act.name %></h2>
<div class="act-main">
<% if @act.act_image %>
<%= image_tag(@act.act_image, class: "act-image") %><br>
<% end %>
<% if @act.description %>
<%= @act.html %><br><br>
<% end %>
</div>
<div class="act-details">

<% act_timeslots = @act.timeslots.all %>
<% bookings = act_timeslots.map { |t| t.bookings } %>
<% bookings = bookings.flatten %>
<% users = bookings.map { |b| b.user.user_image.thumb.url } %>
<% users.uniq! %>

<% if users != [] %>
<h4>People going to see this:</h4>
<% users.each do |user| %>
<%= image_tag(user, class: "user-image-thumb") %> 
<% end %>
<br><br>
<% end %>


<h4>Tags:</h4>
<% @act.keywords.each do |keyword| %>
- <%= link_to keyword.name, event_keyword_path(@event, keyword) %>
<% end %><br><br>

<h4>Times:</h4>

<% @act.timeslots.order(:start_time).each do |timeslot| %>
<%= timeslot.start_time.strftime("%A %l:%M %p") %> - <%= timeslot.end_time.strftime("%l:%M %p")  %>, <%= timeslot.venue.name %> 

<% if can? :update, Timeslot %><%= link_to 'Edit', edit_event_timeslot_path(@event, timeslot) %> - 
<% end %>
<% if can? :delete, Timeslot %>
<%= link_to 'Delete', event_timeslot_path(@event, timeslot), method: :delete, data: {confirm: 'Are you sure you want to delete this time slot?'} %>
<% end %>

<%= form_for(@booking) do |f| %> 
<% if @booking.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this act from being saved:</h2>

  <ul>
    <% @booking.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<%= f.hidden_field :user_id, value: current_user.id %>
<%= f.hidden_field :timeslot_id, value: timeslot.id %>
<%= f.submit 'Add to My Schedule', class: "add-button" %>
<% end %><br>

<% end %>
<br>
<%= link_to 'Back', :back %>
</div>
<br><br>
<% if can? :update, Act %>
<%= link_to "Edit Act Profile", edit_event_act_path(@event, @act) %> - 
<% end %>
<% if can? :create, Timeslot %>
<%= link_to "Add Performance Times", {:controller => "timeslots", :action => "new", :id => @act.id, event: @event } %> 
<% end %>